"""video_ocr_engine 版本与共享常量（复用 engine_config 单一事实源）。"""
from engine_config import (  # noqa: F401 — 引擎域常量直接重导出
    app_data_dir, app_logs_dir, MPS_TO_KMH, SOURCE_TO_KMH,
    DEFAULT_OCR_MODEL, DEFAULT_DECODE_BACKEND, DEFAULT_BUFFER_SIZE,
    DEFAULT_FILL_WIDTH, DEFAULT_FORCE_ASPECT, DEFAULT_FPS_FALLBACK,
    OCR_GAMMA, HYBRID_DECODE_ENV, HYBRID_OCR_ENV, HYBRID_CPU_SPLIT,
    SEG_C, SEG_CALIB_FRAMES, OTSU_FALLBACK_THRESH, DECODE_BATCH_SIZE,
    HYBRID_QUEUE_SIZE, OCR_INFER_QUEUE_SIZE, OCR_BATCH_SIZE,
    OCR_TARGET_H, OCR_RESIZE_TOL, GRAY_RGB_WEIGHTS, OCR_PAD_WIDTH_MIN,
    OCR_PAD_WIDTH_MIN_BY_MODEL, CPU_CORES_SPLIT_THRESHOLD, OCR_ONNX_CHUNK,
    OCR_CTC_CHUNK, TRT_PROFILE_BATCH, TRT_PROFILE_MIN_W, TRT_PROFILE_OPT_W,
    TRT_PROFILE_MAX_W, TRT_WORKSPACE_BYTES, TRT_ENGINE_SM,
)
from engine_config import __version__  # noqa: F401
