name: CI-Probe

on:
  push:
    branches: [ci-probe]
  workflow_dispatch:

jobs:
  probe-windows-latest:
    runs-on: windows-latest
    steps:
      - run: echo "windows-latest OK"
  probe-windows-2022:
    runs-on: windows-2022
    steps:
      - run: echo "windows-2022 OK"
